name: Playwright Tests
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Setup .NET 8 SDK
      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"

      # Intram in folderul proiectului si construim codul
      - name: Build project
        working-directory: ./PlaywrightTests
        run: dotnet build

      # Instalam browserele Playwright folosind executabilul generat
      - name: Ensure browsers are installed
        working-directory: ./PlaywrightTests
        run: pwsh bin/Debug/net8.0/playwright.ps1 install --with-deps

      # Executam testele NUnit
      - name: Run Playwright tests
        working-directory: ./PlaywrightTests
        run: dotnet test

      # Salvam rapoartele in caz de esec sau succes
      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: test-results
          path: PlaywrightTests/TestResults/
          retention-days: 30
